M48
; DRILL file {KiCad 8.0.8} date 2025-03-22T13:35:36-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-03-22T13:35:36-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.8
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X201.25Y-124.005
X201.25Y-129.005
T2
X86.0Y-62.0
X86.0Y-145.0
X202.0Y-62.0
X202.0Y-145.0
M30
